[[git_repo]]
Path = "C:/HIL/ApplicationArea/EEVMerkenich/Modeling/ApplicationBuild/Components"
Url = "git@github.com:ford-innersource/eet.hil.ComponentsLibrary.git"
Branch = "main"

[[git_repo]]
Path = "C:/HIL/ApplicationArea/EEVMerkenich/Modeling/ApplicationBuild/Project"
Url = "git@github.com:ford-innersource/eet.hil.ApplicationProject.git"
Branch = "main"


[[git_repo]]
Path = "C:/HIL/ApplicationArea/EEVMerkenich/Tools/dSPACE/SYNECT/WFMApplicationBuild"
Url = "git@github.com:ford-innersource/swat.wfm-application-build.git"
Branch = "main"

[[git_repo]]
Path = "C:/HIL/ApplicationArea/EEVMerkenich/Modeling/ModelDevelopment/FordHilToolbox"
Url = "git@github.com:ford-innersource/eet.hil.FordHilToolbox.git"
Branch = "NewModelStructure"

[[git_repo]]
Path = "C:/HIL/ApplicationArea/EEVMerkenich/Modeling/ModelDevelopment/InterfaceData"
Url = "git@github.com:ford-innersource/eet.hil.InterfaceData.git"
Branch = "main"



[[git_repo]]
Path = "C:/HIL/ApplicationArea/EEVMerkenich/Modeling/ModelDevelopment/_ECUs"
Url = "git@github.com:ford-innersource/eet.hil.EcuModels.git"
Branch = "main"

[[git_repo]]
Path = "C:/HIL/ApplicationArea/EEVMerkenich/Modeling/ModelDevelopment/_Facility"
Url = "git@github.com:ford-innersource/eet.hil.FacilityModels.git"
Branch = "main"

[[git_repo]]
Path = "C:/HIL/ApplicationArea/EEVMerkenich/Modeling/ModelDevelopment/_Vehicle/_Architecture/_BusSystems"
Url = "git@github.com:ford-innersource/eet.hil.ModelsBusSystems.git"
Branch = "main"

[[git_repo]]
Path = "C:/HIL/ApplicationArea/EEVMerkenich/Modeling/ModelDevelopment/_Vehicle/_Architecture/_Networks"
Url = "git@github.com:ford-innersource/eet.hil.NetworkProjects.git"
Branch = "main"

[[git_repo]]
Path = "C:/HIL/ApplicationArea/EEVMerkenich/Modeling/ModelDevelopment/Generic/ASM"
Url = "git@github.com:ford-innersource/eet.hil.ModelsAsm.git"
Branch = "main"

[[git_repo]]
Path = "C:/HIL/ApplicationArea/EEVMerkenich/Modeling/ModelDevelopment/Generic/Body"
Url = "git@github.com:ford-innersource/eet.hil.ModelsBody.git"
Branch = "main"

[[git_repo]]
Path = "C:/HIL/ApplicationArea/EEVMerkenich/Modeling/ModelDevelopment/Generic/UserInput"
Url = "git@github.com:ford-innersource/eet.hil.ModelsUserInput.git"
Branch = "main"