[[git_repo]]
Path = "C:/HIL/ApplicationArea/EEVMerkenich/Modeling/ModelDevelopment/_ECUs"
Url = "git@github.com:ford-innersource/eet.hil.EcuModels.git"
Branch = "bulu"

[[git_repo]]
Path = "C:/HIL/ApplicationArea/EEVMerkenich/Modeling/ApplicationBuild/Components"
Url = "git@github.com:ford-innersource/eet.hil.ComponentsLibrary.git"
Branch = "main"

[[git_repo]]
Path = "C:/HIL/ApplicationArea/EEVMerkenich/Modeling/ApplicationBuild/Components2"
Url = "git@github.com:ford-innersource/eet.hil.ComponentsLibrary.git"
Branch = "main"

[[svn_repo]]
Name = "Bulu"